name: login2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_auth: ^4.3.0
  firebase_core: ^2.9.0
  get: 4.6.5
  google_sign_in: ^6.0.2
  http: ^0.13.5
  introduction_screen: ^3.1.7
  just_audio: ^0.9.32
  lottie: ^2.3.0
  sqflite: 2.2.8
  path_provider: 2.0.14
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/gambar/
  uses-material-design: true

