// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMS0F1izUpRBLQFY8rg9cM5ropCzNN7cI',
    appId: '1:773975208416:android:d73819d5c23be724e47b85',
    messagingSenderId: '773975208416',
    projectId: 'login2-f370f',
    storageBucket: 'login2-f370f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzJ1ywjXrXBLN_OuRk5OZwyUT2nudEcY',
    appId: '1:773975208416:ios:5253da74546dbf31e47b85',
    messagingSenderId: '773975208416',
    projectId: 'login2-f370f',
    storageBucket: 'login2-f370f.appspot.com',
    androidClientId: '773975208416-1rklrscrerrauug2k61ab38k1uup9t15.apps.googleusercontent.com',
    iosClientId: '773975208416-7v5g6hko56ak59upgvtsqes6bdfc25fc.apps.googleusercontent.com',
    iosBundleId: 'com.azhar.login2',
  );
}
